/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package cloudquery.plugin.sdk;

import io.grpc.Grpc;
import io.grpc.Server;
import io.grpc.InsecureServerCredentials;
import cloudquery.discovery.v1.DiscoveryGrpc;
import java.io.IOException;
import java.util.concurrent.Executors;
import java.util.logging.Level;
import java.util.logging.Logger;

public class DiscoveryServer extends DiscoveryGrpc.DiscoveryImplBase {
    private static final Logger logger = Logger.getLogger(DiscoveryServer.class.getName());
    private Server server;
    private int port = 10002;

    public void start() throws IOException, InterruptedException {
        server = Grpc.newServerBuilderForPort(port, InsecureServerCredentials.create())
                .addService(this)
                .executor(Executors.newFixedThreadPool(1))
                .build();
        server.start();
        logger.log(Level.INFO, "Started on {0}", port);
        server.awaitTermination();
    }
}
