/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package cloudquery.plugin.sdk;

import org.junit.Test;

public class PluginServerTest {
    @Test
    public void NewServer() throws Exception {
        new PluginServer();
    }
}
